route:
  receiver: email-alert

receivers:
- name: email-alert
  email_configs:
  - to: your-email@gmail.com
    from: your-email@gmail.com
    smarthost: smtp.gmail.com:587
    auth_username: your-email@gmail.com
    auth_identity: your-email@gmail.com
    auth_password: your-app-password