- name: Setup and deploy MERN application
  hosts: hosts_list
  become: true

  tasks:

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install required packages
      apt:
        name:
          - git
          - docker.io
        state: present

    - name: Start docker service
      service:
        name: docker
        state: started
        enabled: true

    - name: Create docker network
      docker_network:
        name: todo-network
        state: present

    - name: Run MongoDB container
      docker_container:
        name: todo-mongo
        image: mongo:7
        state: started
        restart_policy: always
        networks:
          - name: todo-network
        volumes:
          - mongo-data:/data/db

    - name: Configure SSH for GitHub access
      copy:
        dest: /root/.ssh/config
        content: |
          Host github.com
            HostName github.com
            User git
            IdentityFile /root/.ssh/github_deploy
        mode: "0600"

    - name: Pull code from private GitHub repository
      git:
        repo: "git@github.com:thientr18/mern-todo-devops.git"
        dest: /root/mern-todo-app
        version: main
        key_file: /root/.ssh/github_deploy
        accept_hostkey: yes

    - name: Create backend .env
      copy:
        dest: /root/mern-todo-app/app/backend/.env
        content: |
          MONGO_URI=mongodb://todo-mongo:27017/todo
          GMAIL_USERNAME=
          GMAIL_PASSWORD=
          SERVER_DOMAIN=
          JWT_SECRET=<0513gVeUv'£
          PORT=8000
        mode: "0600"

    - name: Build and run containers
      shell: docker compose up -d --build
      args:
        chdir: /root/mern-todo-app

    - name: Clean unused docker images
      shell: docker image prune -f