- name: Playbook to install applications
  hosts: hosts_list
  become: true # Run with 'sudo'

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install git
      apt:
        name: git
        state: present

    - name: Install docker
      apt:
        name: docker.io
        state: present
        
    - name: Install docker-compose
      shell: curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose

    - name: Make docker-compose executable
      shell: chmod +x /usr/local/bin/docker-compose

    - name: Pull code from private GitHub repository
      git:
        repo: 'git@github.com:thientr18/mern-todo-devops.git'
        dest: /root/mern-todo-app
        version: main
        key_file: /root/.ssh/github_deploy
        accept_hostkey: yes

    - name: Create docker network
      shell: docker network create todo-network

    - name: Run MongoDB container
      shell: docker run -d --name todo-mongo --network todo-network -v mongo-data:/data/db --restart always mongo:7
    
    - name: Create backend .env file
      copy:
        dest: /root/mern-todo-app/app/backend/.env
        content: |
          MONGO_URI=mongodb://todo-mongo:27017/todo
          GMAIL_USERNAME=
          GMAIL_PASSWORD=
          PORT=8000
          JWT_SECRET=<0513gVeUv'£
          SERVER_IP=
          REACT_APP_API_URL=http://${SERVER_IP}:8000/api
        mode: '0600'

    - name: Run backend and frontend containers
      shell: |
        cd /root/mern-todo-app
        docker-compose up -d --build
      args:
        chdir: /root/mern-todo-app

    - name: Clean up unused Docker images
      shell: docker image prune -f